In [20]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
data=pd.read_csv("titanic.csv")
data

PassengerId                                               Name  Pclass  \
0              1                            Braund, Mr. Owen Harris       3   
1              2  Cumings, Mrs. John Bradley (Florence Briggs Th...       1   
2              3                             Heikkinen, Miss. Laina       3   
3              4       Futrelle, Mrs. Jacques Heath (Lily May Peel)       1   
4              5                           Allen, Mr. William Henry       3   
..           ...                                                ...     ...   
886          887                              Montvila, Rev. Juozas       2   
887          888                       Graham, Miss. Margaret Edith       1   
888          889           Johnston, Miss. Catherine Helen "Carrie"       3   
889          890                              Behr, Mr. Karl Howell       1   
890          891                                Dooley, Mr. Patrick       3   

        Sex   Age  SibSp  Parch            Ticket     Fare Cabin Embarked  \
0      male  22.0      1      0         A/5 21171   7.2500   NaN        S   
1    female  38.0      1      0          PC 17599  71.2833   C85        C   
2    female  26.0      0      0  STON/O2. 3101282   7.9250   NaN        S   
3    female  35.0      1      0            113803  53.1000  C123        S   
4      male  35.0      0      0            373450   8.0500   NaN        S   
..      ...   ...    ...    ...               ...      ...   ...      ...   
886    male  27.0      0      0            211536  13.0000   NaN        S   
887  female  19.0      0      0            112053  30.0000   B42        S   
888  female   NaN      1      2        W./C. 6607  23.4500   NaN        S   
889    male  26.0      0      0            111369  30.0000  C148        C   
890    male  32.0      0      0            370376   7.7500   NaN        Q   

     Survived  
0           0  
1           1  
2           1  
3           1  
4           0  
..        ...  
886         0  
887         1  
888         0  
889         1  
890         0  

[891 rows x 12 columns]

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Name         891 non-null    object 
 2   Pclass       891 non-null    int64  
 3   Sex          891 non-null    object 
 4   Age          714 non-null    float64
 5   SibSp        891 non-null    int64  
 6   Parch        891 non-null    int64  
 7   Ticket       891 non-null    object 
 8   Fare         891 non-null    float64
 9   Cabin        204 non-null    object 
 10  Embarked     889 non-null    object 
 11  Survived     891 non-null    int64  
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


# One Hot Encoding

In [4]:
real_data=data[["Sex","Embarked"]]
real_data

Sex Embarked
0      male        S
1    female        C
2    female        S
3    female        S
4      male        S
..      ...      ...
886    male        S
887  female        S
888  female        S
889    male        C
890    male        Q

[891 rows x 2 columns]

In [5]:
dummies_df=pd.get_dummies(real_data)
dummies_df

Sex_female  Sex_male  Embarked_C  Embarked_Q  Embarked_S
0             0         1           0           0           1
1             1         0           1           0           0
2             1         0           0           0           1
3             1         0           0           0           1
4             0         1           0           0           1
..          ...       ...         ...         ...         ...
886           0         1           0           0           1
887           1         0           0           0           1
888           1         0           0           0           1
889           0         1           1           0           0
890           0         1           0           1           0

[891 rows x 5 columns]

In [6]:
#assign dummies to variable
x=dummies_df
x

Sex_female  Sex_male  Embarked_C  Embarked_Q  Embarked_S
0             0         1           0           0           1
1             1         0           1           0           0
2             1         0           0           0           1
3             1         0           0           0           1
4             0         1           0           0           1
..          ...       ...         ...         ...         ...
886           0         1           0           0           1
887           1         0           0           0           1
888           1         0           0           0           1
889           0         1           1           0           0
890           0         1           0           1           0

[891 rows x 5 columns]

In [7]:
y=data[['Survived']]
y

Survived
0           0
1           1
2           1
3           1
4           0
..        ...
886         0
887         1
888         0
889         1
890         0

[891 rows x 1 columns]

# Splitting data into train and test 

In [8]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

# Feature Scalling

In [9]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [10]:
print(x_train)

[[ 1.37207547 -1.37207547  2.12588331 -0.31426968 -1.62827579]
 [-0.72882288  0.72882288 -0.4703927  -0.31426968  0.61414657]
 [-0.72882288  0.72882288  2.12588331 -0.31426968 -1.62827579]
 ...
 [-0.72882288  0.72882288 -0.4703927   3.18198052 -1.62827579]
 [ 1.37207547 -1.37207547 -0.4703927  -0.31426968  0.61414657]
 [-0.72882288  0.72882288 -0.4703927  -0.31426968  0.61414657]]


In [11]:
print(x_test)

[[-0.72882288  0.72882288  2.12588331 -0.31426968 -1.62827579]
 [-0.72882288  0.72882288 -0.4703927  -0.31426968  0.61414657]
 [-0.72882288  0.72882288 -0.4703927   3.18198052 -1.62827579]
 [ 1.37207547 -1.37207547  2.12588331 -0.31426968 -1.62827579]
 [ 1.37207547 -1.37207547  2.12588331 -0.31426968 -1.62827579]
 [-0.72882288  0.72882288 -0.4703927  -0.31426968  0.61414657]
 [ 1.37207547 -1.37207547 -0.4703927  -0.31426968  0.61414657]
 [ 1.37207547 -1.37207547 -0.4703927  -0.31426968  0.61414657]
 [-0.72882288  0.72882288  2.12588331 -0.31426968 -1.62827579]
 [ 1.37207547 -1.37207547  2.12588331 -0.31426968 -1.62827579]
 [-0.72882288  0.72882288 -0.4703927  -0.31426968  0.61414657]
 [ 1.37207547 -1.37207547 -0.4703927  -0.31426968  0.61414657]
 [-0.72882288  0.72882288 -0.4703927   3.18198052 -1.62827579]
 [ 1.37207547 -1.37207547 -0.4703927  -0.31426968  0.61414657]
 [ 1.37207547 -1.37207547  2.12588331 -0.31426968 -1.62827579]
 [ 1.37207547 -1.37207547 -0.4703927  -0.31426968  0.61

# Logistic Regression Trainig

In [12]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(x_train, y_train)

C:\Users\ASIM\Anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


LogisticRegression(random_state=0)

In [13]:
#on training set
classifier.score(x_train,y_train)

0.7865168539325843

In [14]:
#on test set
classifier.score(x_test,y_test)

0.7877094972067039

In [15]:
y_pred = classifier.predict(x_test)
y_pred

array([0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1,
       1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 0], dtype=int64)

In [16]:
probab=classifier.predict_proba(x_test)
probab

array([[0.70299274, 0.29700726],
       [0.82689212, 0.17310788],
       [0.83831494, 0.16168506],
       [0.16273292, 0.83726708],
       [0.16273292, 0.83726708],
       [0.82689212, 0.17310788],
       [0.28173666, 0.71826334],
       [0.28173666, 0.71826334],
       [0.70299274, 0.29700726],
       [0.16273292, 0.83726708],
       [0.82689212, 0.17310788],
       [0.28173666, 0.71826334],
       [0.83831494, 0.16168506],
       [0.28173666, 0.71826334],
       [0.16273292, 0.83726708],
       [0.28173666, 0.71826334],
       [0.82689212, 0.17310788],
       [0.82689212, 0.17310788],
       [0.82689212, 0.17310788],
       [0.70299274, 0.29700726],
       [0.82689212, 0.17310788],
       [0.28173666, 0.71826334],
       [0.83831494, 0.16168506],
       [0.82689212, 0.17310788],
       [0.28173666, 0.71826334],
       [0.16273292, 0.83726708],
       [0.82689212, 0.17310788],
       [0.28173666, 0.71826334],
       [0.28173666, 0.71826334],
       [0.28173666, 0.71826334],
       [0.

In [17]:
np.argmax(probab[3])

1

In [18]:
plt.scatter(x_train,y_train , marker = 'x' , color = 'black' )
plt.plot(x_train,classifier.predict(x_train),color='cyan')

font1 = {'family':'serif','color':'black','size':20}
font2 = {'family':'serif','color':'green','size':18}

plt.xlabel('sex','embaraked',fontdict = font2)
plt.ylabel('Survived',fontdict = font2)
plt.title('Titanic Survival Classification',fontdict = font1,)
plt.show()

NameError: name 'plt' is not defined